services:
  # Api gateway
  gateway:
    build:
      context: ./backend/gateway/
      dockerfile: Dockerfile
    env_file:
      - ./backend/gateway/.env
    ports:
      - "3000:3000"
    depends_on:
      - products
    networks:
      - public
      - internal


  # Microservices
  # Products microservice
  products:
    build:
      context: ./backend/microservices/products
      dockerfile: Dockerfile
    env_file:
      - ./backend/microservices/products/.env
    networks:
      - internal


networks:
  public:
  internal:
